### ISSUE TITLE
Paper 1.20 에서 에러가 발생합니다.

### ISSUE THREAD

**Issue by zlfn** [monun/heartbeat-coroutines#7]
코드는 아래와 같습니다. (예제 코드와 거의 같습니다.)
```kotlin    
override fun onEnable() {
        HeartbeatScope().launch {
            val suspension = Suspension()
            suspension.delay(3000L)
            logger.info("Hello")
        }
    }
```
Gradle은 아래와 같고 ShadowJar로 빌드했습니다.
```gradle
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.9.0'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'space.zlfn'
version = '0.1'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.2'
    implementation("io.github.monun:heartbeat-coroutines:0.0.5")
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

.....
```
<details>
<summary>전체 Gradle</summary>

```gradle
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.9.0'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'space.zlfn'
version = '0.1'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.2'
    implementation("io.github.monun:heartbeat-coroutines:0.0.5")
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

def targetJavaVersion = 17
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release = targetJavaVersion
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('paper-plugin.yml') {
        expand props
    }
}
compileKotlin {
    kotlinOptions {
        jvmTarget = "17"
    }
}
compileTestKotlin {
    kotlinOptions {
        jvmTarget = "17"
    }
}
```
</details>

이렇게 빌드한 플러그인을 페이퍼 1.20.1#117에서 실행시켰을 때, 아래와 같은 에러가 발생합니다.
```
[20:01:54 ERROR]: Error occurred while enabling HelloMessage v0.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at io.github.monun.heartbeat.coroutines.HeartbeatCoroutineKt.HeartbeatScope(HeartbeatCoroutine.kt:68) ~[HelloMessage-0.1-all.jar:?]
	at space.zlfn.hellomessage.HelloMessage.onEnable(HelloMessage.kt:24) ~[HelloMessage-0.1-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-117]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-117]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.ClassCastException: class io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader cannot be cast to class org.bukkit.plugin.java.PluginClassLoader (io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader and org.bukkit.plugin.java.PluginClassLoader are in unnamed module of loader java.net.URLClassLoader @67424e82)
	at io.github.monun.heartbeat.coroutines.Downstream.pullPlugin(Downstream.kt:26) ~[HelloMessage-0.1-all.jar:?]
	at io.github.monun.heartbeat.coroutines.HeartbeatCoroutine.<clinit>(HeartbeatCoroutine.kt:14) ~[HelloMessage-0.1-all.jar:?]
	... 14 more
```

반면 똑같은 코드를 **1.18로 빌드(ShadowJar)해서 Paper 1.18.2#338에서 실행했을 때는 에러 없이 코드가 작동했습니다.**

코드를 살펴보니 플러그인이 1.18만 지원하는건 아닌 것 같아보였는데, 혹시 버전 의존성이 있을까요?
에러 로그 살펴보니 페이퍼 자체의 버그 같아 보이기도 합니다만... 제가 식견이 짧아 자세히는 모르겠습니다.

실행환경
* OS : Arch Linux x86_64 (6.4.8-arch1-1)
* IDE : IntelliJ IDEA Ultimate 2023.1.3
* JDK : openjdk 20.0.2

**Comment by zlfn** [comment]
방금 테스트해봤는데, 1.19의 경우에도 동일한 에러가 발생합니다.
